apiVersion: v1
kind: Service
metadata:
  name:  Sample-svc
  lables:
    app: docker
  spec:
    type: Nodeport
    ports:
    - port: 80
      protocal: TCP
      nodeport: 30001
    selector:
      app: tomcat

