apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: sample-pod
        image: jenkins
        ports:
        - containerPort: 80    
