apiVersion: v1
kind : Service
metadata:
  name: sample-svc
  labels: 
    app: jenkins
spec:
  type: Nodeport
  ports:
  - port: 8080
    protocal: TCP
    nodeport: 300001
  selector:
    app: jenkins        