apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-rc
spec:
  replicas: 3
  selector: 
    app: nginx
  template:
    metadata:
    labels:
      app: nginx
  spec:
    containers:
    - name:  sample-rc
      image: nginx
      ports:
      - containerport: 80